/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HighlightResponse from './HighlightResponse';

/**
 * The Document model module.
 * @module model/Document
 * @version 1.2.2
 */
class Document {
    /**
     * Constructs a new <code>Document</code>.
     * @alias module:model/Document
     * @param id {String} 
     */
    constructor(id) { 
        
        Document.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Document</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Document} obj Optional instance to populate.
     * @return {module:model/Document} The populated <code>Document</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Document();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('highlights')) {
                obj['highlights'] = ApiClient.convertToType(data['highlights'], [HighlightResponse]);
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], Object);
            }
            if (data.hasOwnProperty('rankingExplanation')) {
                obj['rankingExplanation'] = ApiClient.convertToType(data['rankingExplanation'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Document.prototype['id'] = undefined;

/**
 * @member {Number} score
 */
Document.prototype['score'] = undefined;

/**
 * @member {Array.<module:model/HighlightResponse>} highlights
 */
Document.prototype['highlights'] = undefined;

/**
 * @member {Object} attributes
 */
Document.prototype['attributes'] = undefined;

/**
 * @member {Object} rankingExplanation
 */
Document.prototype['rankingExplanation'] = undefined;






export default Document;

