/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftSearchClientJavascript) {
      root.UpliftSearchClientJavascript = {};
    }
    root.UpliftSearchClientJavascript.FacetResponseValues = factory(root.UpliftSearchClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The FacetResponseValues model module.
   * @module model/FacetResponseValues
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>FacetResponseValues</code>.
   * @alias module:model/FacetResponseValues
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FacetResponseValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacetResponseValues} obj Optional instance to populate.
   * @return {module:model/FacetResponseValues} The populated <code>FacetResponseValues</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('numResults'))
        obj.numResults = ApiClient.convertToType(data['numResults'], 'Number');
    }
    return obj;
  }

  /**
   * Particular value of attribute
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Number of documents containing this value for this attribute
   * @member {Number} numResults
   */
  exports.prototype.numResults = undefined;

  return exports;

}));
