/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FacetResponseValues from './FacetResponseValues';

/**
 * The FacetResponse model module.
 * @module model/FacetResponse
 * @version 1.2.2
 */
class FacetResponse {
    /**
     * Constructs a new <code>FacetResponse</code>.
     * @alias module:model/FacetResponse
     */
    constructor() { 
        
        FacetResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FacetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FacetResponse} obj Optional instance to populate.
     * @return {module:model/FacetResponse} The populated <code>FacetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FacetResponse();

            if (data.hasOwnProperty('attributeName')) {
                obj['attributeName'] = ApiClient.convertToType(data['attributeName'], 'String');
            }
            if (data.hasOwnProperty('numDistinctValues')) {
                obj['numDistinctValues'] = ApiClient.convertToType(data['numDistinctValues'], 'Number');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [FacetResponseValues]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} attributeName
 */
FacetResponse.prototype['attributeName'] = undefined;

/**
 * Total number of distinct values this attribute holds
 * @member {Number} numDistinctValues
 */
FacetResponse.prototype['numDistinctValues'] = undefined;

/**
 * @member {Array.<module:model/FacetResponseValues>} values
 */
FacetResponse.prototype['values'] = undefined;






export default FacetResponse;

