/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.FacetParams = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The FacetParams model module.
   * @module model/FacetParams
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>FacetParams</code>.
   * @alias module:model/FacetParams
   * @class
   * @param attributes {Array.<String>} 
   */
  var exports = function(attributes) {
    var _this = this;

    _this['attributes'] = attributes;
  };

  /**
   * Constructs a <code>FacetParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacetParams} obj Optional instance to populate.
   * @return {module:model/FacetParams} The populated <code>FacetParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('maxFacets')) {
        obj['maxFacets'] = ApiClient.convertToType(data['maxFacets'], 'Number');
      }
      if (data.hasOwnProperty('maxValuePerFacet')) {
        obj['maxValuePerFacet'] = ApiClient.convertToType(data['maxValuePerFacet'], 'Number');
      }
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], ['String']);
      }
      if (data.hasOwnProperty('sortFacetValuesBy')) {
        obj['sortFacetValuesBy'] = ApiClient.convertToType(data['sortFacetValuesBy'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} maxFacets
   */
  exports.prototype['maxFacets'] = undefined;
  /**
   * @member {Number} maxValuePerFacet
   */
  exports.prototype['maxValuePerFacet'] = undefined;
  /**
   * @member {Array.<String>} attributes
   */
  exports.prototype['attributes'] = undefined;
  /**
   * @member {module:model/FacetParams.SortFacetValuesByEnum} sortFacetValuesBy
   * @default 'count'
   */
  exports.prototype['sortFacetValuesBy'] = 'count';


  /**
   * Allowed values for the <code>sortFacetValuesBy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SortFacetValuesByEnum = {
    /**
     * value: "alpha"
     * @const
     */
    "alpha": "alpha",
    /**
     * value: "count"
     * @const
     */
    "count": "count"  };


  return exports;
}));


