/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.FacetResponseValues = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The FacetResponseValues model module.
   * @module model/FacetResponseValues
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>FacetResponseValues</code>.
   * @alias module:model/FacetResponseValues
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>FacetResponseValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacetResponseValues} obj Optional instance to populate.
   * @return {module:model/FacetResponseValues} The populated <code>FacetResponseValues</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('numResults')) {
        obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Particular value of attribute
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Number of documents containing this value for this attribute
   * @member {Number} numResults
   */
  exports.prototype['numResults'] = undefined;



  return exports;
}));


