/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FacetResponseValues model module.
 * @module model/FacetResponseValues
 * @version 1.2.2
 */
class FacetResponseValues {
    /**
     * Constructs a new <code>FacetResponseValues</code>.
     * @alias module:model/FacetResponseValues
     */
    constructor() { 
        
        FacetResponseValues.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FacetResponseValues</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FacetResponseValues} obj Optional instance to populate.
     * @return {module:model/FacetResponseValues} The populated <code>FacetResponseValues</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FacetResponseValues();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('numResults')) {
                obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Particular value of attribute
 * @member {String} name
 */
FacetResponseValues.prototype['name'] = undefined;

/**
 * Number of documents containing this value for this attribute
 * @member {Number} numResults
 */
FacetResponseValues.prototype['numResults'] = undefined;






export default FacetResponseValues;

