/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FetchParams from './FetchParams';
import RequestParams from './RequestParams';

/**
 * The FetchRequest model module.
 * @module model/FetchRequest
 * @version 1.2.2
 */
class FetchRequest {
    /**
     * Constructs a new <code>FetchRequest</code>.
     * @alias module:model/FetchRequest
     * @param fetchParams {module:model/FetchParams} 
     * @param requestParams {module:model/RequestParams} 
     */
    constructor(fetchParams, requestParams) { 
        
        FetchRequest.initialize(this, fetchParams, requestParams);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fetchParams, requestParams) { 
        obj['fetchParams'] = fetchParams;
        obj['requestParams'] = requestParams;
    }

    /**
     * Constructs a <code>FetchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FetchRequest} obj Optional instance to populate.
     * @return {module:model/FetchRequest} The populated <code>FetchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchRequest();

            if (data.hasOwnProperty('fetchParams')) {
                obj['fetchParams'] = FetchParams.constructFromObject(data['fetchParams']);
            }
            if (data.hasOwnProperty('requestParams')) {
                obj['requestParams'] = RequestParams.constructFromObject(data['requestParams']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/FetchParams} fetchParams
 */
FetchRequest.prototype['fetchParams'] = undefined;

/**
 * @member {module:model/RequestParams} requestParams
 */
FetchRequest.prototype['requestParams'] = undefined;






export default FetchRequest;

