/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.FetchParams = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The FetchParams model module.
   * @module model/FetchParams
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>FetchParams</code>.
   * @alias module:model/FetchParams
   * @class
   * @param attributesToRetrieve {Array.<String>} List of attributes to return for each document. By default, returns all attributes. Returning all attributes can increase response size and latency.
   * @param fieldName {String} This field will be used to match the 'fieldValue'
   * @param fieldValue {String} This value will be used to match in 'fieldName'
   */
  var exports = function(attributesToRetrieve, fieldName, fieldValue) {
    var _this = this;

    _this['attributesToRetrieve'] = attributesToRetrieve;
    _this['fieldName'] = fieldName;
    _this['fieldValue'] = fieldValue;
  };

  /**
   * Constructs a <code>FetchParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FetchParams} obj Optional instance to populate.
   * @return {module:model/FetchParams} The populated <code>FetchParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('attributesToRetrieve')) {
        obj['attributesToRetrieve'] = ApiClient.convertToType(data['attributesToRetrieve'], ['String']);
      }
      if (data.hasOwnProperty('fieldName')) {
        obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
      }
      if (data.hasOwnProperty('fieldValue')) {
        obj['fieldValue'] = ApiClient.convertToType(data['fieldValue'], 'String');
      }
    }
    return obj;
  }

  /**
   * List of attributes to return for each document. By default, returns all attributes. Returning all attributes can increase response size and latency.
   * @member {Array.<String>} attributesToRetrieve
   */
  exports.prototype['attributesToRetrieve'] = undefined;
  /**
   * This field will be used to match the 'fieldValue'
   * @member {String} fieldName
   * @default 'id'
   */
  exports.prototype['fieldName'] = 'id';
  /**
   * This value will be used to match in 'fieldName'
   * @member {String} fieldValue
   */
  exports.prototype['fieldValue'] = undefined;



  return exports;
}));


