/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Document from './Document';
import FetchParams from './FetchParams';
import QueryPerformance from './QueryPerformance';

/**
 * The FetchResponse model module.
 * @module model/FetchResponse
 * @version 1.2.2
 */
class FetchResponse {
    /**
     * Constructs a new <code>FetchResponse</code>.
     * @alias module:model/FetchResponse
     * @param performance {module:model/QueryPerformance} 
     * @param result {module:model/Document} 
     */
    constructor(performance, result) { 
        
        FetchResponse.initialize(this, performance, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, performance, result) { 
        obj['performance'] = performance;
        obj['result'] = result;
    }

    /**
     * Constructs a <code>FetchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FetchResponse} obj Optional instance to populate.
     * @return {module:model/FetchResponse} The populated <code>FetchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchResponse();

            if (data.hasOwnProperty('performance')) {
                obj['performance'] = QueryPerformance.constructFromObject(data['performance']);
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = Document.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('fetchParams')) {
                obj['fetchParams'] = FetchParams.constructFromObject(data['fetchParams']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/QueryPerformance} performance
 */
FetchResponse.prototype['performance'] = undefined;

/**
 * @member {module:model/Document} result
 */
FetchResponse.prototype['result'] = undefined;

/**
 * @member {module:model/FetchParams} fetchParams
 */
FetchResponse.prototype['fetchParams'] = undefined;






export default FetchResponse;

