/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HighlightResponse model module.
 * @module model/HighlightResponse
 * @version 1.2.2
 */
class HighlightResponse {
    /**
     * Constructs a new <code>HighlightResponse</code>.
     * Highlight response for a field
     * @alias module:model/HighlightResponse
     */
    constructor() { 
        
        HighlightResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HighlightResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HighlightResponse} obj Optional instance to populate.
     * @return {module:model/HighlightResponse} The populated <code>HighlightResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HighlightResponse();

            if (data.hasOwnProperty('fieldName')) {
                obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
            }
            if (data.hasOwnProperty('highlightText')) {
                obj['highlightText'] = ApiClient.convertToType(data['highlightText'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} fieldName
 */
HighlightResponse.prototype['fieldName'] = undefined;

/**
 * @member {Array.<String>} highlightText
 */
HighlightResponse.prototype['highlightText'] = undefined;






export default HighlightResponse;

