/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftSearchClientJavascript) {
      root.UpliftSearchClientJavascript = {};
    }
    root.UpliftSearchClientJavascript.PaginationParams = factory(root.UpliftSearchClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PaginationParams model module.
   * @module model/PaginationParams
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>PaginationParams</code>.
   * Pagination configuration
   * @alias module:model/PaginationParams
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PaginationParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaginationParams} obj Optional instance to populate.
   * @return {module:model/PaginationParams} The populated <code>PaginationParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('hitsPerPage'))
        obj.hitsPerPage = ApiClient.convertToType(data['hitsPerPage'], 'Number');
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} hitsPerPage
   * @default 10
   */
  exports.prototype.hitsPerPage = 10;

  /**
   * @member {Number} page
   * @default 0
   */
  exports.prototype.page = 0;

  return exports;

}));
