/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.PaginationParams = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The PaginationParams model module.
   * @module model/PaginationParams
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>PaginationParams</code>.
   * Pagination configuration
   * @alias module:model/PaginationParams
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>PaginationParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaginationParams} obj Optional instance to populate.
   * @return {module:model/PaginationParams} The populated <code>PaginationParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('hitsPerPage')) {
        obj['hitsPerPage'] = ApiClient.convertToType(data['hitsPerPage'], 'Number');
      }
      if (data.hasOwnProperty('page')) {
        obj['page'] = ApiClient.convertToType(data['page'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} hitsPerPage
   * @default 10
   */
  exports.prototype['hitsPerPage'] = 10;
  /**
   * @member {Number} page
   * @default 0
   */
  exports.prototype['page'] = 0;



  return exports;
}));


