/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaginationParams model module.
 * @module model/PaginationParams
 * @version 1.2.2
 */
class PaginationParams {
    /**
     * Constructs a new <code>PaginationParams</code>.
     * Pagination configuration
     * @alias module:model/PaginationParams
     */
    constructor() { 
        
        PaginationParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginationParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginationParams} obj Optional instance to populate.
     * @return {module:model/PaginationParams} The populated <code>PaginationParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationParams();

            if (data.hasOwnProperty('hitsPerPage')) {
                obj['hitsPerPage'] = ApiClient.convertToType(data['hitsPerPage'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} hitsPerPage
 * @default 10
 */
PaginationParams.prototype['hitsPerPage'] = 10;

/**
 * @member {Number} page
 * @default 0
 */
PaginationParams.prototype['page'] = 0;






export default PaginationParams;

