/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftSearchClientJavascript) {
      root.UpliftSearchClientJavascript = {};
    }
    root.UpliftSearchClientJavascript.PersonalizationParams = factory(root.UpliftSearchClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PersonalizationParams model module.
   * @module model/PersonalizationParams
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>PersonalizationParams</code>.
   * @alias module:model/PersonalizationParams
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PersonalizationParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PersonalizationParams} obj Optional instance to populate.
   * @return {module:model/PersonalizationParams} The populated <code>PersonalizationParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('userToken'))
        obj.userToken = ApiClient.convertToType(data['userToken'], 'String');
      if (data.hasOwnProperty('enablePersonalization'))
        obj.enablePersonalization = ApiClient.convertToType(data['enablePersonalization'], 'Boolean');
    }
    return obj;
  }

  /**
   * A token identifying the user. Only required if 'enablePersonalization' is 'true'
   * @member {String} userToken
   */
  exports.prototype.userToken = undefined;

  /**
   * Whether to enable personalization or not
   * @member {Boolean} enablePersonalization
   * @default false
   */
  exports.prototype.enablePersonalization = false;

  return exports;

}));
