/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryPerformance model module.
 * @module model/QueryPerformance
 * @version 1.2.2
 */
class QueryPerformance {
    /**
     * Constructs a new <code>QueryPerformance</code>.
     * Data about the performance of the query
     * @alias module:model/QueryPerformance
     */
    constructor() { 
        
        QueryPerformance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryPerformance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryPerformance} obj Optional instance to populate.
     * @return {module:model/QueryPerformance} The populated <code>QueryPerformance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryPerformance();

            if (data.hasOwnProperty('processingTime')) {
                obj['processingTime'] = ApiClient.convertToType(data['processingTime'], 'Number');
            }
            if (data.hasOwnProperty('timeOut')) {
                obj['timeOut'] = ApiClient.convertToType(data['timeOut'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} processingTime
 */
QueryPerformance.prototype['processingTime'] = undefined;

/**
 * @member {Boolean} timeOut
 */
QueryPerformance.prototype['timeOut'] = undefined;






export default QueryPerformance;

