/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RankingParams model module.
 * @module model/RankingParams
 * @version 1.2.2
 */
class RankingParams {
    /**
     * Constructs a new <code>RankingParams</code>.
     * Ranking criteria
     * @alias module:model/RankingParams
     */
    constructor() { 
        
        RankingParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RankingParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RankingParams} obj Optional instance to populate.
     * @return {module:model/RankingParams} The populated <code>RankingParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RankingParams();

            if (data.hasOwnProperty('relevanceType')) {
                obj['relevanceType'] = ApiClient.convertToType(data['relevanceType'], 'String');
            }
            if (data.hasOwnProperty('attributeName')) {
                obj['attributeName'] = ApiClient.convertToType(data['attributeName'], 'String');
            }
            if (data.hasOwnProperty('rankModifier')) {
                obj['rankModifier'] = ApiClient.convertToType(data['rankModifier'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Type of ranking
 * @member {module:model/RankingParams.RelevanceTypeEnum} relevanceType
 * @default 'relevance'
 */
RankingParams.prototype['relevanceType'] = 'relevance';

/**
 * Name of attribute to use for ranking. Only used if relevanceType is 'attribute'
 * @member {String} attributeName
 */
RankingParams.prototype['attributeName'] = undefined;

/**
 * @member {module:model/RankingParams.RankModifierEnum} rankModifier
 * @default 'desc'
 */
RankingParams.prototype['rankModifier'] = 'desc';





/**
 * Allowed values for the <code>relevanceType</code> property.
 * @enum {String}
 * @readonly
 */
RankingParams['RelevanceTypeEnum'] = {

    /**
     * value: "relevance"
     * @const
     */
    "relevance": "relevance",

    /**
     * value: "attribute"
     * @const
     */
    "attribute": "attribute"
};


/**
 * Allowed values for the <code>rankModifier</code> property.
 * @enum {String}
 * @readonly
 */
RankingParams['RankModifierEnum'] = {

    /**
     * value: "asc"
     * @const
     */
    "asc": "asc",

    /**
     * value: "desc"
     * @const
     */
    "desc": "desc"
};



export default RankingParams;

