/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftSearchClientJavascript) {
      root.UpliftSearchClientJavascript = {};
    }
    root.UpliftSearchClientJavascript.RankingParams = factory(root.UpliftSearchClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RankingParams model module.
   * @module model/RankingParams
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>RankingParams</code>.
   * Ranking criteria
   * @alias module:model/RankingParams
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RankingParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RankingParams} obj Optional instance to populate.
   * @return {module:model/RankingParams} The populated <code>RankingParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('relevanceType'))
        obj.relevanceType = ApiClient.convertToType(data['relevanceType'], 'String');
      if (data.hasOwnProperty('attributeName'))
        obj.attributeName = ApiClient.convertToType(data['attributeName'], 'String');
      if (data.hasOwnProperty('rankModifier'))
        obj.rankModifier = ApiClient.convertToType(data['rankModifier'], 'String');
    }
    return obj;
  }

  /**
   * Type of ranking
   * @member {module:model/RankingParams.RelevanceTypeEnum} relevanceType
   * @default 'relevance'
   */
  exports.prototype.relevanceType = 'relevance';

  /**
   * Name of attribute to use for ranking. Only used if relevanceType is 'attribute'
   * @member {String} attributeName
   */
  exports.prototype.attributeName = undefined;

  /**
   * @member {module:model/RankingParams.RankModifierEnum} rankModifier
   * @default 'desc'
   */
  exports.prototype.rankModifier = 'desc';


  /**
   * Allowed values for the <code>relevanceType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RelevanceTypeEnum = {
    /**
     * value: "relevance"
     * @const
     */
    relevance: "relevance",

    /**
     * value: "attribute"
     * @const
     */
    attribute: "attribute"
  };


  /**
   * Allowed values for the <code>rankModifier</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RankModifierEnum = {
    /**
     * value: "asc"
     * @const
     */
    asc: "asc",

    /**
     * value: "desc"
     * @const
     */
    desc: "desc"
  };

  return exports;

}));
