/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.RecommendationContext = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RecommendationContext model module.
   * @module model/RecommendationContext
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>RecommendationContext</code>.
   * A context object passed in request. Currently the following context types are supported: Product Id, An arbitrary text. Arbitrary text should be used to find recommendations for free-flowing text (e.g. blogs)
   * @alias module:model/RecommendationContext
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RecommendationContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecommendationContext} obj Optional instance to populate.
   * @return {module:model/RecommendationContext} The populated <code>RecommendationContext</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
    }
    return obj;
  }

  /**
   * Context property name
   * @member {module:model/RecommendationContext.NameEnum} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Context value
   * @member {String} value
   */
  exports.prototype['value'] = undefined;


  /**
   * Allowed values for the <code>name</code> property.
   * @enum {String}
   * @readonly
   */
  exports.NameEnum = {
    /**
     * value: "product_id"
     * @const
     */
    "product_id": "product_id",
    /**
     * value: "text"
     * @const
     */
    "text": "text"  };


  return exports;
}));


