/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RecommendationParams', 'model/RequestParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RecommendationParams'), require('./RequestParams'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.RecommendationRequest = factory(root.UpliftCatalogClientJavascript.ApiClient, root.UpliftCatalogClientJavascript.RecommendationParams, root.UpliftCatalogClientJavascript.RequestParams);
  }
}(this, function(ApiClient, RecommendationParams, RequestParams) {
  'use strict';



  /**
   * The RecommendationRequest model module.
   * @module model/RecommendationRequest
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>RecommendationRequest</code>.
   * Recommendation request
   * @alias module:model/RecommendationRequest
   * @class
   * @param recommendationParams {module:model/RecommendationParams} 
   * @param requestParams {module:model/RequestParams} 
   */
  var exports = function(recommendationParams, requestParams) {
    var _this = this;

    _this['recommendationParams'] = recommendationParams;
    _this['requestParams'] = requestParams;
  };

  /**
   * Constructs a <code>RecommendationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecommendationRequest} obj Optional instance to populate.
   * @return {module:model/RecommendationRequest} The populated <code>RecommendationRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('recommendationParams')) {
        obj['recommendationParams'] = RecommendationParams.constructFromObject(data['recommendationParams']);
      }
      if (data.hasOwnProperty('requestParams')) {
        obj['requestParams'] = RequestParams.constructFromObject(data['requestParams']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RecommendationParams} recommendationParams
   */
  exports.prototype['recommendationParams'] = undefined;
  /**
   * @member {module:model/RequestParams} requestParams
   */
  exports.prototype['requestParams'] = undefined;



  return exports;
}));


