/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestParams model module.
 * @module model/RequestParams
 * @version 1.2.2
 */
class RequestParams {
    /**
     * Constructs a new <code>RequestParams</code>.
     * @alias module:model/RequestParams
     */
    constructor() { 
        
        RequestParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestParams} obj Optional instance to populate.
     * @return {module:model/RequestParams} The populated <code>RequestParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestParams();

            if (data.hasOwnProperty('returnParams')) {
                obj['returnParams'] = ApiClient.convertToType(data['returnParams'], 'Boolean');
            }
            if (data.hasOwnProperty('returnRankingExplanation')) {
                obj['returnRankingExplanation'] = ApiClient.convertToType(data['returnRankingExplanation'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Whether to return the original request in the response
 * @member {Boolean} returnParams
 * @default false
 */
RequestParams.prototype['returnParams'] = false;

/**
 * Whether to return reasons on why a particular result was returned. Caution - This will significantly increase the response size and latency.
 * @member {Boolean} returnRankingExplanation
 * @default false
 */
RequestParams.prototype['returnRankingExplanation'] = false;






export default RequestParams;

