/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.RequestParams = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RequestParams model module.
   * @module model/RequestParams
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>RequestParams</code>.
   * @alias module:model/RequestParams
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RequestParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestParams} obj Optional instance to populate.
   * @return {module:model/RequestParams} The populated <code>RequestParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('returnParams')) {
        obj['returnParams'] = ApiClient.convertToType(data['returnParams'], 'Boolean');
      }
      if (data.hasOwnProperty('returnRankingExplanation')) {
        obj['returnRankingExplanation'] = ApiClient.convertToType(data['returnRankingExplanation'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Whether to return the original request in the response
   * @member {Boolean} returnParams
   * @default false
   */
  exports.prototype['returnParams'] = false;
  /**
   * Whether to return reasons on why a particular result was returned. Caution - This will significantly increase the response size and latency.
   * @member {Boolean} returnRankingExplanation
   * @default false
   */
  exports.prototype['returnRankingExplanation'] = false;



  return exports;
}));


