/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchHighlightParams model module.
 * @module model/SearchHighlightParams
 * @version 1.2.2
 */
class SearchHighlightParams {
    /**
     * Constructs a new <code>SearchHighlightParams</code>.
     * @alias module:model/SearchHighlightParams
     * @param attributeNames {Array.<String>} Attributes to use for highlighting matches
     */
    constructor(attributeNames) { 
        
        SearchHighlightParams.initialize(this, attributeNames);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributeNames) { 
        obj['attributeNames'] = attributeNames;
    }

    /**
     * Constructs a <code>SearchHighlightParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchHighlightParams} obj Optional instance to populate.
     * @return {module:model/SearchHighlightParams} The populated <code>SearchHighlightParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchHighlightParams();

            if (data.hasOwnProperty('attributeNames')) {
                obj['attributeNames'] = ApiClient.convertToType(data['attributeNames'], ['String']);
            }
            if (data.hasOwnProperty('preTag')) {
                obj['preTag'] = ApiClient.convertToType(data['preTag'], 'String');
            }
            if (data.hasOwnProperty('postTag')) {
                obj['postTag'] = ApiClient.convertToType(data['postTag'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Attributes to use for highlighting matches
 * @member {Array.<String>} attributeNames
 */
SearchHighlightParams.prototype['attributeNames'] = undefined;

/**
 * @member {String} preTag
 * @default '<em>'
 */
SearchHighlightParams.prototype['preTag'] = '<em>';

/**
 * @member {String} postTag
 * @default '</em>'
 */
SearchHighlightParams.prototype['postTag'] = '</em>';






export default SearchHighlightParams;

