/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RequestParams', 'model/SearchParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RequestParams'), require('./SearchParams'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.SearchRequest = factory(root.UpliftCatalogClientJavascript.ApiClient, root.UpliftCatalogClientJavascript.RequestParams, root.UpliftCatalogClientJavascript.SearchParams);
  }
}(this, function(ApiClient, RequestParams, SearchParams) {
  'use strict';



  /**
   * The SearchRequest model module.
   * @module model/SearchRequest
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>SearchRequest</code>.
   * Search request
   * @alias module:model/SearchRequest
   * @class
   * @param searchParams {module:model/SearchParams} 
   * @param requestParams {module:model/RequestParams} 
   */
  var exports = function(searchParams, requestParams) {
    var _this = this;

    _this['searchParams'] = searchParams;
    _this['requestParams'] = requestParams;
  };

  /**
   * Constructs a <code>SearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchRequest} obj Optional instance to populate.
   * @return {module:model/SearchRequest} The populated <code>SearchRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('searchParams')) {
        obj['searchParams'] = SearchParams.constructFromObject(data['searchParams']);
      }
      if (data.hasOwnProperty('requestParams')) {
        obj['requestParams'] = RequestParams.constructFromObject(data['requestParams']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SearchParams} searchParams
   */
  exports.prototype['searchParams'] = undefined;
  /**
   * @member {module:model/RequestParams} requestParams
   */
  exports.prototype['requestParams'] = undefined;



  return exports;
}));


