/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Document from './Document';
import FacetResponse from './FacetResponse';
import QueryPerformance from './QueryPerformance';
import SearchParams from './SearchParams';

/**
 * The SearchResponse model module.
 * @module model/SearchResponse
 * @version 1.2.2
 */
class SearchResponse {
    /**
     * Constructs a new <code>SearchResponse</code>.
     * Response from a search request
     * @alias module:model/SearchResponse
     * @param numResults {Number} 
     * @param results {Array.<module:model/Document>} 
     * @param performance {module:model/QueryPerformance} 
     */
    constructor(numResults, results, performance) { 
        
        SearchResponse.initialize(this, numResults, results, performance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, numResults, results, performance) { 
        obj['numResults'] = numResults;
        obj['results'] = results;
        obj['performance'] = performance;
    }

    /**
     * Constructs a <code>SearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchResponse} obj Optional instance to populate.
     * @return {module:model/SearchResponse} The populated <code>SearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchResponse();

            if (data.hasOwnProperty('numResults')) {
                obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
            }
            if (data.hasOwnProperty('numPages')) {
                obj['numPages'] = ApiClient.convertToType(data['numPages'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [Document]);
            }
            if (data.hasOwnProperty('performance')) {
                obj['performance'] = QueryPerformance.constructFromObject(data['performance']);
            }
            if (data.hasOwnProperty('facets')) {
                obj['facets'] = FacetResponse.constructFromObject(data['facets']);
            }
            if (data.hasOwnProperty('searchParams')) {
                obj['searchParams'] = SearchParams.constructFromObject(data['searchParams']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} numResults
 */
SearchResponse.prototype['numResults'] = undefined;

/**
 * Number of pages of content. Formula is ceiling(numResults/hitsPerPage)
 * @member {Number} numPages
 */
SearchResponse.prototype['numPages'] = undefined;

/**
 * @member {Array.<module:model/Document>} results
 */
SearchResponse.prototype['results'] = undefined;

/**
 * @member {module:model/QueryPerformance} performance
 */
SearchResponse.prototype['performance'] = undefined;

/**
 * @member {module:model/FacetResponse} facets
 */
SearchResponse.prototype['facets'] = undefined;

/**
 * @member {module:model/SearchParams} searchParams
 */
SearchResponse.prototype['searchParams'] = undefined;






export default SearchResponse;

