/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.SearchHighlightParams = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SearchHighlightParams model module.
   * @module model/SearchHighlightParams
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>SearchHighlightParams</code>.
   * @alias module:model/SearchHighlightParams
   * @class
   * @param attributeNames {Array.<String>} Attributes to use for highlighting matches
   */
  var exports = function(attributeNames) {
    var _this = this;

    _this['attributeNames'] = attributeNames;
  };

  /**
   * Constructs a <code>SearchHighlightParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchHighlightParams} obj Optional instance to populate.
   * @return {module:model/SearchHighlightParams} The populated <code>SearchHighlightParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('attributeNames')) {
        obj['attributeNames'] = ApiClient.convertToType(data['attributeNames'], ['String']);
      }
      if (data.hasOwnProperty('preTag')) {
        obj['preTag'] = ApiClient.convertToType(data['preTag'], 'String');
      }
      if (data.hasOwnProperty('postTag')) {
        obj['postTag'] = ApiClient.convertToType(data['postTag'], 'String');
      }
    }
    return obj;
  }

  /**
   * Attributes to use for highlighting matches
   * @member {Array.<String>} attributeNames
   */
  exports.prototype['attributeNames'] = undefined;
  /**
   * @member {String} preTag
   * @default '<em>'
   */
  exports.prototype['preTag'] = '<em>';
  /**
   * @member {String} postTag
   * @default '</em>'
   */
  exports.prototype['postTag'] = '</em>';



  return exports;
}));


