/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestParams from './RequestParams';
import SuggestParams from './SuggestParams';

/**
 * The SuggestRequest model module.
 * @module model/SuggestRequest
 * @version 1.2.2
 */
class SuggestRequest {
    /**
     * Constructs a new <code>SuggestRequest</code>.
     * Suggest request
     * @alias module:model/SuggestRequest
     * @param suggestParams {module:model/SuggestParams} 
     * @param requestParams {module:model/RequestParams} 
     */
    constructor(suggestParams, requestParams) { 
        
        SuggestRequest.initialize(this, suggestParams, requestParams);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, suggestParams, requestParams) { 
        obj['suggestParams'] = suggestParams;
        obj['requestParams'] = requestParams;
    }

    /**
     * Constructs a <code>SuggestRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SuggestRequest} obj Optional instance to populate.
     * @return {module:model/SuggestRequest} The populated <code>SuggestRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuggestRequest();

            if (data.hasOwnProperty('suggestParams')) {
                obj['suggestParams'] = SuggestParams.constructFromObject(data['suggestParams']);
            }
            if (data.hasOwnProperty('requestParams')) {
                obj['requestParams'] = RequestParams.constructFromObject(data['requestParams']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SuggestParams} suggestParams
 */
SuggestRequest.prototype['suggestParams'] = undefined;

/**
 * @member {module:model/RequestParams} requestParams
 */
SuggestRequest.prototype['requestParams'] = undefined;






export default SuggestRequest;

