/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftSearchClientJavascript) {
      root.UpliftSearchClientJavascript = {};
    }
    root.UpliftSearchClientJavascript.SuggestHighlightParams = factory(root.UpliftSearchClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SuggestHighlightParams model module.
   * @module model/SuggestHighlightParams
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>SuggestHighlightParams</code>.
   * @alias module:model/SuggestHighlightParams
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SuggestHighlightParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestHighlightParams} obj Optional instance to populate.
   * @return {module:model/SuggestHighlightParams} The populated <code>SuggestHighlightParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('preTag'))
        obj.preTag = ApiClient.convertToType(data['preTag'], 'String');
      if (data.hasOwnProperty('postTag'))
        obj.postTag = ApiClient.convertToType(data['postTag'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} preTag
   * @default '<em>'
   */
  exports.prototype.preTag = '<em>';

  /**
   * @member {String} postTag
   * @default '</em>'
   */
  exports.prototype.postTag = '</em>';

  return exports;

}));
