/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Document', 'model/QueryPerformance', 'model/SuggestParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Document'), require('./QueryPerformance'), require('./SuggestParams'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.SuggestResponse = factory(root.UpliftCatalogClientJavascript.ApiClient, root.UpliftCatalogClientJavascript.Document, root.UpliftCatalogClientJavascript.QueryPerformance, root.UpliftCatalogClientJavascript.SuggestParams);
  }
}(this, function(ApiClient, Document, QueryPerformance, SuggestParams) {
  'use strict';



  /**
   * The SuggestResponse model module.
   * @module model/SuggestResponse
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>SuggestResponse</code>.
   * Response from a suggest request
   * @alias module:model/SuggestResponse
   * @class
   * @param numResults {Number} 
   * @param results {Array.<module:model/Document>} 
   * @param performance {module:model/QueryPerformance} 
   */
  var exports = function(numResults, results, performance) {
    var _this = this;

    _this['numResults'] = numResults;
    _this['results'] = results;
    _this['performance'] = performance;
  };

  /**
   * Constructs a <code>SuggestResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestResponse} obj Optional instance to populate.
   * @return {module:model/SuggestResponse} The populated <code>SuggestResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('numResults')) {
        obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
      }
      if (data.hasOwnProperty('numPages')) {
        obj['numPages'] = ApiClient.convertToType(data['numPages'], 'Number');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [Document]);
      }
      if (data.hasOwnProperty('performance')) {
        obj['performance'] = QueryPerformance.constructFromObject(data['performance']);
      }
      if (data.hasOwnProperty('suggestParams')) {
        obj['suggestParams'] = SuggestParams.constructFromObject(data['suggestParams']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} numResults
   */
  exports.prototype['numResults'] = undefined;
  /**
   * Number of pages of content. Formula is ceiling(numResults/hitsPerPage)
   * @member {Number} numPages
   */
  exports.prototype['numPages'] = undefined;
  /**
   * @member {Array.<module:model/Document>} results
   */
  exports.prototype['results'] = undefined;
  /**
   * @member {module:model/QueryPerformance} performance
   */
  exports.prototype['performance'] = undefined;
  /**
   * @member {module:model/SuggestParams} suggestParams
   */
  exports.prototype['suggestParams'] = undefined;



  return exports;
}));


