/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RequestParams', 'model/SuggestParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RequestParams'), require('./SuggestParams'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.SuggestRequest = factory(root.UpliftCatalogClientJavascript.ApiClient, root.UpliftCatalogClientJavascript.RequestParams, root.UpliftCatalogClientJavascript.SuggestParams);
  }
}(this, function(ApiClient, RequestParams, SuggestParams) {
  'use strict';



  /**
   * The SuggestRequest model module.
   * @module model/SuggestRequest
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>SuggestRequest</code>.
   * Suggest request
   * @alias module:model/SuggestRequest
   * @class
   * @param suggestParams {module:model/SuggestParams} 
   * @param requestParams {module:model/RequestParams} 
   */
  var exports = function(suggestParams, requestParams) {
    var _this = this;

    _this['suggestParams'] = suggestParams;
    _this['requestParams'] = requestParams;
  };

  /**
   * Constructs a <code>SuggestRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestRequest} obj Optional instance to populate.
   * @return {module:model/SuggestRequest} The populated <code>SuggestRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('suggestParams')) {
        obj['suggestParams'] = SuggestParams.constructFromObject(data['suggestParams']);
      }
      if (data.hasOwnProperty('requestParams')) {
        obj['requestParams'] = RequestParams.constructFromObject(data['requestParams']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SuggestParams} suggestParams
   */
  exports.prototype['suggestParams'] = undefined;
  /**
   * @member {module:model/RequestParams} requestParams
   */
  exports.prototype['requestParams'] = undefined;



  return exports;
}));


