/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SuggestHighlightParams model module.
 * @module model/SuggestHighlightParams
 * @version 1.2.2
 */
class SuggestHighlightParams {
    /**
     * Constructs a new <code>SuggestHighlightParams</code>.
     * @alias module:model/SuggestHighlightParams
     */
    constructor() { 
        
        SuggestHighlightParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SuggestHighlightParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SuggestHighlightParams} obj Optional instance to populate.
     * @return {module:model/SuggestHighlightParams} The populated <code>SuggestHighlightParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuggestHighlightParams();

            if (data.hasOwnProperty('preTag')) {
                obj['preTag'] = ApiClient.convertToType(data['preTag'], 'String');
            }
            if (data.hasOwnProperty('postTag')) {
                obj['postTag'] = ApiClient.convertToType(data['postTag'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} preTag
 * @default '<em>'
 */
SuggestHighlightParams.prototype['preTag'] = '<em>';

/**
 * @member {String} postTag
 * @default '</em>'
 */
SuggestHighlightParams.prototype['postTag'] = '</em>';






export default SuggestHighlightParams;

