/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaginationParams from './PaginationParams';
import SuggestHighlightParams from './SuggestHighlightParams';
import SuggestParamsSuggestionSource from './SuggestParamsSuggestionSource';

/**
 * The SuggestParams model module.
 * @module model/SuggestParams
 * @version 1.2.2
 */
class SuggestParams {
    /**
     * Constructs a new <code>SuggestParams</code>.
     * @alias module:model/SuggestParams
     * @param keyphrase {String} Query keyphrase. Empty keyphrase returns no result.
     * @param suggestionType {module:model/SuggestParams.SuggestionTypeEnum} Type of suggestion to be returned
     * @param suggestionSource {module:model/SuggestParamsSuggestionSource} 
     * @param language {String} Language iso code
     */
    constructor(keyphrase, suggestionType, suggestionSource, language) { 
        
        SuggestParams.initialize(this, keyphrase, suggestionType, suggestionSource, language);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, keyphrase, suggestionType, suggestionSource, language) { 
        obj['keyphrase'] = keyphrase;
        obj['suggestionType'] = suggestionType;
        obj['suggestionSource'] = suggestionSource;
        obj['language'] = language;
    }

    /**
     * Constructs a <code>SuggestParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SuggestParams} obj Optional instance to populate.
     * @return {module:model/SuggestParams} The populated <code>SuggestParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuggestParams();

            if (data.hasOwnProperty('keyphrase')) {
                obj['keyphrase'] = ApiClient.convertToType(data['keyphrase'], 'String');
            }
            if (data.hasOwnProperty('suggestionType')) {
                obj['suggestionType'] = ApiClient.convertToType(data['suggestionType'], 'String');
            }
            if (data.hasOwnProperty('suggestionSource')) {
                obj['suggestionSource'] = SuggestParamsSuggestionSource.constructFromObject(data['suggestionSource']);
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('highlightParams')) {
                obj['highlightParams'] = SuggestHighlightParams.constructFromObject(data['highlightParams']);
            }
            if (data.hasOwnProperty('paginationParams')) {
                obj['paginationParams'] = PaginationParams.constructFromObject(data['paginationParams']);
            }
        }
        return obj;
    }


}

/**
 * Query keyphrase. Empty keyphrase returns no result.
 * @member {String} keyphrase
 */
SuggestParams.prototype['keyphrase'] = undefined;

/**
 * Type of suggestion to be returned
 * @member {module:model/SuggestParams.SuggestionTypeEnum} suggestionType
 */
SuggestParams.prototype['suggestionType'] = undefined;

/**
 * @member {module:model/SuggestParamsSuggestionSource} suggestionSource
 */
SuggestParams.prototype['suggestionSource'] = undefined;

/**
 * Language iso code
 * @member {String} language
 */
SuggestParams.prototype['language'] = undefined;

/**
 * @member {module:model/SuggestHighlightParams} highlightParams
 */
SuggestParams.prototype['highlightParams'] = undefined;

/**
 * @member {module:model/PaginationParams} paginationParams
 */
SuggestParams.prototype['paginationParams'] = undefined;





/**
 * Allowed values for the <code>suggestionType</code> property.
 * @enum {String}
 * @readonly
 */
SuggestParams['SuggestionTypeEnum'] = {

    /**
     * value: "completion"
     * @const
     */
    "completion": "completion",

    /**
     * value: "spellCorrection"
     * @const
     */
    "spellCorrection": "spellCorrection"
};



export default SuggestParams;

