/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RequestParams', 'model/SuggestParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RequestParams'), require('./SuggestParams'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftSearchClientJavascript) {
      root.UpliftSearchClientJavascript = {};
    }
    root.UpliftSearchClientJavascript.SuggestRequest = factory(root.UpliftSearchClientJavascript.ApiClient, root.UpliftSearchClientJavascript.RequestParams, root.UpliftSearchClientJavascript.SuggestParams);
  }
}(this, function(ApiClient, RequestParams, SuggestParams) {
  'use strict';

  /**
   * The SuggestRequest model module.
   * @module model/SuggestRequest
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>SuggestRequest</code>.
   * Suggest request
   * @alias module:model/SuggestRequest
   * @class
   * @param suggestParams {module:model/SuggestParams} 
   * @param requestParams {module:model/RequestParams} 
   */
  var exports = function(suggestParams, requestParams) {
    this.suggestParams = suggestParams;
    this.requestParams = requestParams;
  };

  /**
   * Constructs a <code>SuggestRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestRequest} obj Optional instance to populate.
   * @return {module:model/SuggestRequest} The populated <code>SuggestRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('suggestParams'))
        obj.suggestParams = SuggestParams.constructFromObject(data['suggestParams']);
      if (data.hasOwnProperty('requestParams'))
        obj.requestParams = RequestParams.constructFromObject(data['requestParams']);
    }
    return obj;
  }

  /**
   * @member {module:model/SuggestParams} suggestParams
   */
  exports.prototype.suggestParams = undefined;

  /**
   * @member {module:model/RequestParams} requestParams
   */
  exports.prototype.requestParams = undefined;

  return exports;

}));
