/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.SuggestParamsSuggestionSource = factory(root.UpliftCatalogClientJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SuggestParamsSuggestionSource model module.
   * @module model/SuggestParamsSuggestionSource
   * @version 1.2.2
   */

  /**
   * Constructs a new <code>SuggestParamsSuggestionSource</code>.
   * Describe the source of suggestions
   * @alias module:model/SuggestParamsSuggestionSource
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SuggestParamsSuggestionSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestParamsSuggestionSource} obj Optional instance to populate.
   * @return {module:model/SuggestParamsSuggestionSource} The populated <code>SuggestParamsSuggestionSource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('sourceName')) {
        obj['sourceName'] = ApiClient.convertToType(data['sourceName'], 'String');
      }
      if (data.hasOwnProperty('attributeName')) {
        obj['attributeName'] = ApiClient.convertToType(data['attributeName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SuggestParamsSuggestionSource.SourceNameEnum} sourceName
   */
  exports.prototype['sourceName'] = undefined;
  /**
   * Attribute to be used as source of suggestions
   * @member {String} attributeName
   */
  exports.prototype['attributeName'] = undefined;


  /**
   * Allowed values for the <code>sourceName</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SourceNameEnum = {
    /**
     * value: "recentSearchesByUser"
     * @const
     */
    "recentSearchesByUser": "recentSearchesByUser",
    /**
     * value: "topSearches"
     * @const
     */
    "topSearches": "topSearches",
    /**
     * value: "attribute"
     * @const
     */
    "attribute": "attribute"  };


  return exports;
}));


