/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SuggestRequest', 'model/SuggestResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SuggestRequest'), require('../model/SuggestResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.UpliftCatalogClientJavascript) {
      root.UpliftCatalogClientJavascript = {};
    }
    root.UpliftCatalogClientJavascript.SuggestApi = factory(root.UpliftCatalogClientJavascript.ApiClient, root.UpliftCatalogClientJavascript.SuggestRequest, root.UpliftCatalogClientJavascript.SuggestResponse);
  }
}(this, function(ApiClient, SuggestRequest, SuggestResponse) {
  'use strict';

  /**
   * Suggest service.
   * @module api/SuggestApi
   * @version 1.3.0
   */

  /**
   * Constructs a new SuggestApi. 
   * @alias module:api/SuggestApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * @param {String} domainId Domain Id
     * @param {String} catalogId Catalog Id
     * @param {module:model/SuggestRequest} suggestRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SuggestResponse} and HTTP response
     */
    this.suggestWithHttpInfo = function(domainId, catalogId, suggestRequest) {
      var postBody = suggestRequest;
      // verify the required parameter 'domainId' is set
      if (domainId === undefined || domainId === null) {
        throw new Error("Missing the required parameter 'domainId' when calling suggest");
      }
      // verify the required parameter 'catalogId' is set
      if (catalogId === undefined || catalogId === null) {
        throw new Error("Missing the required parameter 'catalogId' when calling suggest");
      }
      // verify the required parameter 'suggestRequest' is set
      if (suggestRequest === undefined || suggestRequest === null) {
        throw new Error("Missing the required parameter 'suggestRequest' when calling suggest");
      }

      var pathParams = {
        'domainId': domainId,
        'catalogId': catalogId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SuggestResponse;
      return this.apiClient.callApi(
        '/v1/domain/{domainId}/catalog/{catalogId}/suggest', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} domainId Domain Id
     * @param {String} catalogId Catalog Id
     * @param {module:model/SuggestRequest} suggestRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SuggestResponse}
     */
    this.suggest = function(domainId, catalogId, suggestRequest) {
      return this.suggestWithHttpInfo(domainId, catalogId, suggestRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Options Call
     * @param {String} domainId Domain Id
     * @param {String} catalogId Catalog Id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.v1DomainDomainIdCatalogCatalogIdSuggestOptionsWithHttpInfo = function(domainId, catalogId) {
      var postBody = null;
      // verify the required parameter 'domainId' is set
      if (domainId === undefined || domainId === null) {
        throw new Error("Missing the required parameter 'domainId' when calling v1DomainDomainIdCatalogCatalogIdSuggestOptions");
      }
      // verify the required parameter 'catalogId' is set
      if (catalogId === undefined || catalogId === null) {
        throw new Error("Missing the required parameter 'catalogId' when calling v1DomainDomainIdCatalogCatalogIdSuggestOptions");
      }

      var pathParams = {
        'domainId': domainId,
        'catalogId': catalogId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;
      return this.apiClient.callApi(
        '/v1/domain/{domainId}/catalog/{catalogId}/suggest', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Options Call
     * @param {String} domainId Domain Id
     * @param {String} catalogId Catalog Id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.v1DomainDomainIdCatalogCatalogIdSuggestOptions = function(domainId, catalogId) {
      return this.v1DomainDomainIdCatalogCatalogIdSuggestOptionsWithHttpInfo(domainId, catalogId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
