/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftSearchClientJavascript);
  }
}(this, function(expect, UpliftSearchClientJavascript) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FacetParams', function() {
      beforeEach(function() {
        instance = new UpliftSearchClientJavascript.FacetParams();
      });

      it('should create an instance of FacetParams', function() {
        // TODO: update the code to test FacetParams
        expect(instance).to.be.a(UpliftSearchClientJavascript.FacetParams);
      });

      it('should have the property maxFacets (base name: "maxFacets")', function() {
        // TODO: update the code to test the property maxFacets
        expect(instance).to.have.property('maxFacets');
        // expect(instance.maxFacets).to.be(expectedValueLiteral);
      });

      it('should have the property maxValuePerFacet (base name: "maxValuePerFacet")', function() {
        // TODO: update the code to test the property maxValuePerFacet
        expect(instance).to.have.property('maxValuePerFacet');
        // expect(instance.maxValuePerFacet).to.be(expectedValueLiteral);
      });

      it('should have the property attributes (base name: "attributes")', function() {
        // TODO: update the code to test the property attributes
        expect(instance).to.have.property('attributes');
        // expect(instance.attributes).to.be(expectedValueLiteral);
      });

      it('should have the property sortFacetValuesBy (base name: "sortFacetValuesBy")', function() {
        // TODO: update the code to test the property sortFacetValuesBy
        expect(instance).to.have.property('sortFacetValuesBy');
        // expect(instance.sortFacetValuesBy).to.be(expectedValueLiteral);
      });

    });
  });

}));
