/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftCatalogClientJavascript);
  }
}(this, function(expect, UpliftCatalogClientJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UpliftCatalogClientJavascript.FetchResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FetchResponse', function() {
    it('should create an instance of FetchResponse', function() {
      // uncomment below and update the code to test FetchResponse
      //var instane = new UpliftCatalogClientJavascript.FetchResponse();
      //expect(instance).to.be.a(UpliftCatalogClientJavascript.FetchResponse);
    });

    it('should have the property performance (base name: "performance")', function() {
      // uncomment below and update the code to test the property performance
      //var instane = new UpliftCatalogClientJavascript.FetchResponse();
      //expect(instance).to.be();
    });

    it('should have the property result (base name: "result")', function() {
      // uncomment below and update the code to test the property result
      //var instane = new UpliftCatalogClientJavascript.FetchResponse();
      //expect(instance).to.be();
    });

    it('should have the property fetchParams (base name: "fetchParams")', function() {
      // uncomment below and update the code to test the property fetchParams
      //var instane = new UpliftCatalogClientJavascript.FetchResponse();
      //expect(instance).to.be();
    });

  });

}));
