/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftSearchClientJavascript);
  }
}(this, function(expect, UpliftSearchClientJavascript) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HighlightResponse', function() {
      beforeEach(function() {
        instance = new UpliftSearchClientJavascript.HighlightResponse();
      });

      it('should create an instance of HighlightResponse', function() {
        // TODO: update the code to test HighlightResponse
        expect(instance).to.be.a(UpliftSearchClientJavascript.HighlightResponse);
      });

      it('should have the property fieldName (base name: "fieldName")', function() {
        // TODO: update the code to test the property fieldName
        expect(instance).to.have.property('fieldName');
        // expect(instance.fieldName).to.be(expectedValueLiteral);
      });

      it('should have the property highlightText (base name: "highlightText")', function() {
        // TODO: update the code to test the property highlightText
        expect(instance).to.have.property('highlightText');
        // expect(instance.highlightText).to.be(expectedValueLiteral);
      });

    });
  });

}));
