/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftCatalogClientJavascript);
  }
}(this, function(expect, UpliftCatalogClientJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UpliftCatalogClientJavascript.RecommendationParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecommendationParams', function() {
    it('should create an instance of RecommendationParams', function() {
      // uncomment below and update the code to test RecommendationParams
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be.a(UpliftCatalogClientJavascript.RecommendationParams);
    });

    it('should have the property recommendationType (base name: "recommendationType")', function() {
      // uncomment below and update the code to test the property recommendationType
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property context (base name: "context")', function() {
      // uncomment below and update the code to test the property context
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property attributesToRetrieve (base name: "attributesToRetrieve")', function() {
      // uncomment below and update the code to test the property attributesToRetrieve
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property paginationParams (base name: "paginationParams")', function() {
      // uncomment below and update the code to test the property paginationParams
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property rankingParams (base name: "rankingParams")', function() {
      // uncomment below and update the code to test the property rankingParams
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

    it('should have the property personalizationParams (base name: "personalizationParams")', function() {
      // uncomment below and update the code to test the property personalizationParams
      //var instance = new UpliftCatalogClientJavascript.RecommendationParams();
      //expect(instance).to.be();
    });

  });

}));
