/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftSearchClientJavascript);
  }
}(this, function(expect, UpliftSearchClientJavascript) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SuggestRequest', function() {
      beforeEach(function() {
        instance = new UpliftSearchClientJavascript.SuggestRequest();
      });

      it('should create an instance of SuggestRequest', function() {
        // TODO: update the code to test SuggestRequest
        expect(instance).to.be.a(UpliftSearchClientJavascript.SuggestRequest);
      });

      it('should have the property suggestParams (base name: "suggestParams")', function() {
        // TODO: update the code to test the property suggestParams
        expect(instance).to.have.property('suggestParams');
        // expect(instance.suggestParams).to.be(expectedValueLiteral);
      });

      it('should have the property requestParams (base name: "requestParams")', function() {
        // TODO: update the code to test the property requestParams
        expect(instance).to.have.property('requestParams');
        // expect(instance.requestParams).to.be(expectedValueLiteral);
      });

    });
  });

}));
