/*
 * Search API
 * This is the API for getting search results.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftSearchClientJavascript);
  }
}(this, function(expect, UpliftSearchClientJavascript) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SuggestParams', function() {
      beforeEach(function() {
        instance = new UpliftSearchClientJavascript.SuggestParams();
      });

      it('should create an instance of SuggestParams', function() {
        // TODO: update the code to test SuggestParams
        expect(instance).to.be.a(UpliftSearchClientJavascript.SuggestParams);
      });

      it('should have the property keyphrase (base name: "keyphrase")', function() {
        // TODO: update the code to test the property keyphrase
        expect(instance).to.have.property('keyphrase');
        // expect(instance.keyphrase).to.be(expectedValueLiteral);
      });

      it('should have the property suggestionType (base name: "suggestionType")', function() {
        // TODO: update the code to test the property suggestionType
        expect(instance).to.have.property('suggestionType');
        // expect(instance.suggestionType).to.be(expectedValueLiteral);
      });

      it('should have the property suggestionSource (base name: "suggestionSource")', function() {
        // TODO: update the code to test the property suggestionSource
        expect(instance).to.have.property('suggestionSource');
        // expect(instance.suggestionSource).to.be(expectedValueLiteral);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property highlightParams (base name: "highlightParams")', function() {
        // TODO: update the code to test the property highlightParams
        expect(instance).to.have.property('highlightParams');
        // expect(instance.highlightParams).to.be(expectedValueLiteral);
      });

      it('should have the property paginationParams (base name: "paginationParams")', function() {
        // TODO: update the code to test the property paginationParams
        expect(instance).to.have.property('paginationParams');
        // expect(instance.paginationParams).to.be(expectedValueLiteral);
      });

    });
  });

}));
