/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Document', 'model/FacetParams', 'model/FacetResponse', 'model/FacetResponseValues', 'model/FetchParams', 'model/FetchRequest', 'model/FetchResponse', 'model/HighlightResponse', 'model/PaginationParams', 'model/PersonalizationParams', 'model/QueryPerformance', 'model/RankingParams', 'model/RecommendationContext', 'model/RecommendationParams', 'model/RecommendationRequest', 'model/RecommendationResponse', 'model/RequestParams', 'model/SearchHighlightParams', 'model/SearchParams', 'model/SearchRequest', 'model/SearchResponse', 'model/SuggestHighlightParams', 'model/SuggestParams', 'model/SuggestParamsSuggestionSource', 'model/SuggestRequest', 'model/SuggestResponse', 'api/FetchApi', 'api/RecommendationApi', 'api/SearchApi', 'api/SuggestApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Document'), require('./model/FacetParams'), require('./model/FacetResponse'), require('./model/FacetResponseValues'), require('./model/FetchParams'), require('./model/FetchRequest'), require('./model/FetchResponse'), require('./model/HighlightResponse'), require('./model/PaginationParams'), require('./model/PersonalizationParams'), require('./model/QueryPerformance'), require('./model/RankingParams'), require('./model/RecommendationContext'), require('./model/RecommendationParams'), require('./model/RecommendationRequest'), require('./model/RecommendationResponse'), require('./model/RequestParams'), require('./model/SearchHighlightParams'), require('./model/SearchParams'), require('./model/SearchRequest'), require('./model/SearchResponse'), require('./model/SuggestHighlightParams'), require('./model/SuggestParams'), require('./model/SuggestParamsSuggestionSource'), require('./model/SuggestRequest'), require('./model/SuggestResponse'), require('./api/FetchApi'), require('./api/RecommendationApi'), require('./api/SearchApi'), require('./api/SuggestApi'));
  }
}(function(ApiClient, Document, FacetParams, FacetResponse, FacetResponseValues, FetchParams, FetchRequest, FetchResponse, HighlightResponse, PaginationParams, PersonalizationParams, QueryPerformance, RankingParams, RecommendationContext, RecommendationParams, RecommendationRequest, RecommendationResponse, RequestParams, SearchHighlightParams, SearchParams, SearchRequest, SearchResponse, SuggestHighlightParams, SuggestParams, SuggestParamsSuggestionSource, SuggestRequest, SuggestResponse, FetchApi, RecommendationApi, SearchApi, SuggestApi) {
  'use strict';

  /**
   * Uplift Catalog API Client.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var UpliftCatalogClientJavascript = require('index'); // See note below*.
   * var xxxSvc = new UpliftCatalogClientJavascript.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new UpliftCatalogClientJavascript.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new UpliftCatalogClientJavascript.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new UpliftCatalogClientJavascript.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.3.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Document model constructor.
     * @property {module:model/Document}
     */
    Document: Document,
    /**
     * The FacetParams model constructor.
     * @property {module:model/FacetParams}
     */
    FacetParams: FacetParams,
    /**
     * The FacetResponse model constructor.
     * @property {module:model/FacetResponse}
     */
    FacetResponse: FacetResponse,
    /**
     * The FacetResponseValues model constructor.
     * @property {module:model/FacetResponseValues}
     */
    FacetResponseValues: FacetResponseValues,
    /**
     * The FetchParams model constructor.
     * @property {module:model/FetchParams}
     */
    FetchParams: FetchParams,
    /**
     * The FetchRequest model constructor.
     * @property {module:model/FetchRequest}
     */
    FetchRequest: FetchRequest,
    /**
     * The FetchResponse model constructor.
     * @property {module:model/FetchResponse}
     */
    FetchResponse: FetchResponse,
    /**
     * The HighlightResponse model constructor.
     * @property {module:model/HighlightResponse}
     */
    HighlightResponse: HighlightResponse,
    /**
     * The PaginationParams model constructor.
     * @property {module:model/PaginationParams}
     */
    PaginationParams: PaginationParams,
    /**
     * The PersonalizationParams model constructor.
     * @property {module:model/PersonalizationParams}
     */
    PersonalizationParams: PersonalizationParams,
    /**
     * The QueryPerformance model constructor.
     * @property {module:model/QueryPerformance}
     */
    QueryPerformance: QueryPerformance,
    /**
     * The RankingParams model constructor.
     * @property {module:model/RankingParams}
     */
    RankingParams: RankingParams,
    /**
     * The RecommendationContext model constructor.
     * @property {module:model/RecommendationContext}
     */
    RecommendationContext: RecommendationContext,
    /**
     * The RecommendationParams model constructor.
     * @property {module:model/RecommendationParams}
     */
    RecommendationParams: RecommendationParams,
    /**
     * The RecommendationRequest model constructor.
     * @property {module:model/RecommendationRequest}
     */
    RecommendationRequest: RecommendationRequest,
    /**
     * The RecommendationResponse model constructor.
     * @property {module:model/RecommendationResponse}
     */
    RecommendationResponse: RecommendationResponse,
    /**
     * The RequestParams model constructor.
     * @property {module:model/RequestParams}
     */
    RequestParams: RequestParams,
    /**
     * The SearchHighlightParams model constructor.
     * @property {module:model/SearchHighlightParams}
     */
    SearchHighlightParams: SearchHighlightParams,
    /**
     * The SearchParams model constructor.
     * @property {module:model/SearchParams}
     */
    SearchParams: SearchParams,
    /**
     * The SearchRequest model constructor.
     * @property {module:model/SearchRequest}
     */
    SearchRequest: SearchRequest,
    /**
     * The SearchResponse model constructor.
     * @property {module:model/SearchResponse}
     */
    SearchResponse: SearchResponse,
    /**
     * The SuggestHighlightParams model constructor.
     * @property {module:model/SuggestHighlightParams}
     */
    SuggestHighlightParams: SuggestHighlightParams,
    /**
     * The SuggestParams model constructor.
     * @property {module:model/SuggestParams}
     */
    SuggestParams: SuggestParams,
    /**
     * The SuggestParamsSuggestionSource model constructor.
     * @property {module:model/SuggestParamsSuggestionSource}
     */
    SuggestParamsSuggestionSource: SuggestParamsSuggestionSource,
    /**
     * The SuggestRequest model constructor.
     * @property {module:model/SuggestRequest}
     */
    SuggestRequest: SuggestRequest,
    /**
     * The SuggestResponse model constructor.
     * @property {module:model/SuggestResponse}
     */
    SuggestResponse: SuggestResponse,
    /**
     * The FetchApi service constructor.
     * @property {module:api/FetchApi}
     */
    FetchApi: FetchApi,
    /**
     * The RecommendationApi service constructor.
     * @property {module:api/RecommendationApi}
     */
    RecommendationApi: RecommendationApi,
    /**
     * The SearchApi service constructor.
     * @property {module:api/SearchApi}
     */
    SearchApi: SearchApi,
    /**
     * The SuggestApi service constructor.
     * @property {module:api/SuggestApi}
     */
    SuggestApi: SuggestApi
  };

  return exports;
}));
