/**
 * Catalog API
 * This is the API for retrieving items from your catalog.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ajit.singh@discoverlift.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpliftCatalogClientJavascript);
  }
}(this, function(expect, UpliftCatalogClientJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UpliftCatalogClientJavascript.RecommendationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecommendationApi', function() {
    describe('getRecommendations', function() {
      it('should call getRecommendations successfully', function(done) {
        //uncomment below and update the code to test getRecommendations
        //instance.getRecommendations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainDomainIdCatalogCatalogIdRecommendationOptions', function() {
      it('should call v1DomainDomainIdCatalogCatalogIdRecommendationOptions successfully', function(done) {
        //uncomment below and update the code to test v1DomainDomainIdCatalogCatalogIdRecommendationOptions
        //instance.v1DomainDomainIdCatalogCatalogIdRecommendationOptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
